apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map
  namespace: dev-release-team-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:a25718f54e07956153e8bde1c286020c19cdbe22fb03bc2f05f6113a7fc4f048
        name: container-image
        resources: {}
status: {}
